# Generated by Django 4.1.7 on 2023-03-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='addres',
        ),
    ]
